from django.urls import path
from . import frontend_views

v = frontend_views  # shorthand

urlpatterns = [
    path('login/', v.login_view, name='login'),
    path('logout/', v.logout_view, name='logout'),
    path('', v.dashboard, name='dashboard'),
    path('dashboard/', v.dashboard, name='dashboard'),
    path('profile/', v.profile, name='profile'),

    # Companies (super admin)
    path('companies/', v.company_list, name='company_list'),
    path('companies/add/', v.company_create, name='company_add'),
    path('companies/<int:pk>/', v.company_detail, name='company_detail'),
    path('companies/<int:pk>/edit/', v.company_edit, name='company_edit'),
    path('companies/<int:pk>/toggle-active/', v.company_toggle_active, name='company_toggle_active'),
    path('invite/<str:token>/', v.company_invite_accept, name='company_invite_accept'),

    # Client CRM
    path('clients/', v.client_list, name='client_list'),
    path('clients/add/', v.client_form, name='client_add'),
    path('clients/<int:pk>/', v.client_detail, name='client_detail'),
    path('clients/<int:pk>/edit/', v.client_form, name='client_edit'),
    path('contacts/', v.contact_list, name='contact_list'),
    path('contacts/', v.contact_list, name='contacts_list'),
    path('contacts/add/', v.contacts_form, name='contacts_add'),
    path('contacts/<int:pk>/', v.contacts_detail, name='contacts_detail'),
    path('contacts/<int:pk>/edit/', v.contacts_form, name='contacts_edit'),
    path('contacts/<int:pk>/delete/', v.generic_delete, {'key': 'contacts'}, name='contacts_delete'),

    # Project 360
    path('projects/', v.project_list, name='project_list'),
    path('projects/add/', v.project_form, name='project_add'),
    path('projects/<int:pk>/', v.project_detail, name='project_detail'),
    path('projects/<int:pk>/edit/', v.project_form, name='project_edit'),
    path('tasks/', v.task_list, name='task_list'),
    path('tasks/add/', v.task_form, name='task_add'),
    path('tasks/<int:pk>/edit/', v.task_form, name='task_edit'),
    path('milestones/', v.milestones_list, name='milestones_list'),
    path('milestones/add/', v.milestones_form, name='milestones_add'),
    path('milestones/<int:pk>/', v.milestones_detail, name='milestones_detail'),
    path('milestones/<int:pk>/edit/', v.milestones_form, name='milestones_edit'),
    path('milestones/<int:pk>/delete/', v.generic_delete, {'key': 'milestones'}, name='milestones_delete'),
    path('deliverables/', v.deliverables_list, name='deliverables_list'),
    path('deliverables/add/', v.deliverables_form, name='deliverables_add'),
    path('deliverables/<int:pk>/', v.deliverables_detail, name='deliverables_detail'),
    path('deliverables/<int:pk>/edit/', v.deliverables_form, name='deliverables_edit'),
    path('deliverables/<int:pk>/delete/', v.generic_delete, {'key': 'deliverables'}, name='deliverables_delete'),

    # Employee Operations
    path('employees/', v.employee_list, name='employee_list'),
    path('employees/<int:pk>/', v.employee_detail, name='employee_detail'),
    path('timesheets/', v.timesheet_list, name='timesheets_list'),
    path('timesheets/add/', v.timesheet_form, name='timesheets_add'),
    path('timesheets/<int:pk>/', v.timesheet_detail, name='timesheets_detail'),
    path('timesheets/<int:pk>/edit/', v.timesheet_form, name='timesheets_edit'),
    path('timesheets/<int:pk>/delete/', v.generic_delete, {'key': 'timesheets'}, name='timesheets_delete'),
    path('leaves/', v.leave_list, name='leaves_list'),
    path('leaves/add/', v.leave_form, name='leaves_add'),
    path('leaves/<int:pk>/', v.leave_detail, name='leaves_detail'),
    path('leaves/<int:pk>/edit/', v.leave_form, name='leaves_edit'),
    path('leaves/<int:pk>/delete/', v.generic_delete, {'key': 'leaves'}, name='leaves_delete'),
    path('attendance/', v.attendance_list, name='attendance_list'),
    path('attendance/add/', v.attendance_form, name='attendance_add'),
    path('attendance/<int:pk>/', v.attendance_detail, name='attendance_detail'),
    path('attendance/<int:pk>/edit/', v.attendance_form, name='attendance_edit'),
    path('attendance/<int:pk>/delete/', v.generic_delete, {'key': 'attendance'}, name='attendance_delete'),

    # Collaboration
    path('meetings/', v.meetings_list, name='meetings_list'),
    path('meetings/add/', v.meetings_form, name='meetings_add'),
    path('meetings/<int:pk>/', v.meetings_detail, name='meetings_detail'),
    path('meetings/<int:pk>/edit/', v.meetings_form, name='meetings_edit'),
    path('meetings/<int:pk>/delete/', v.generic_delete, {'key': 'meetings'}, name='meetings_delete'),
    path('documents/', v.documents_list, name='documents_list'),
    path('documents/add/', v.documents_form, name='documents_add'),
    path('documents/<int:pk>/', v.documents_detail, name='documents_detail'),
    path('documents/<int:pk>/edit/', v.documents_form, name='documents_edit'),
    path('documents/<int:pk>/delete/', v.generic_delete, {'key': 'documents'}, name='documents_delete'),
    path('team/', v.team_list, name='team_list'),
    path('team/add/', v.team_form, name='team_add'),
    path('team/<int:pk>/', v.team_detail, name='team_detail'),
    path('team/<int:pk>/edit/', v.team_form, name='team_edit'),
    path('team/<int:pk>/delete/', v.generic_delete, {'key': 'team'}, name='team_delete'),

    # Finance
    path('invoices/', v.invoices_list, name='invoices_list'),
    path('invoices/add/', v.invoices_form, name='invoices_add'),
    path('invoices/<int:pk>/', v.invoices_detail, name='invoices_detail'),
    path('invoices/<int:pk>/edit/', v.invoices_form, name='invoices_edit'),
    path('invoices/<int:pk>/delete/', v.generic_delete, {'key': 'invoices'}, name='invoices_delete'),
    path('payments/', v.payments_list, name='payments_list'),
    path('payments/add/', v.payments_form, name='payments_add'),
    path('payments/<int:pk>/', v.payments_detail, name='payments_detail'),
    path('payments/<int:pk>/edit/', v.payments_form, name='payments_edit'),
    path('payments/<int:pk>/delete/', v.generic_delete, {'key': 'payments'}, name='payments_delete'),
    path('expenses/', v.expenses_list, name='expenses_list'),
    path('expenses/add/', v.expenses_form, name='expenses_add'),
    path('expenses/<int:pk>/', v.expenses_detail, name='expenses_detail'),
    path('expenses/<int:pk>/edit/', v.expenses_form, name='expenses_edit'),
    path('expenses/<int:pk>/delete/', v.generic_delete, {'key': 'expenses'}, name='expenses_delete'),

    # Issues & Risks
    path('issues/', v.issues_list, name='issues_list'),
    path('issues/add/', v.issues_form, name='issues_add'),
    path('issues/<int:pk>/', v.issues_detail, name='issues_detail'),
    path('issues/<int:pk>/edit/', v.issues_form, name='issues_edit'),
    path('issues/<int:pk>/delete/', v.generic_delete, {'key': 'issues'}, name='issues_delete'),
    path('risks/', v.risks_list, name='risks_list'),
    path('risks/add/', v.risks_form, name='risks_add'),
    path('risks/<int:pk>/', v.risks_detail, name='risks_detail'),
    path('risks/<int:pk>/edit/', v.risks_form, name='risks_edit'),
    path('risks/<int:pk>/delete/', v.generic_delete, {'key': 'risks'}, name='risks_delete'),
    path('change-requests/', v.change_requests_list, name='change_requests_list'),
    path('change-requests/add/', v.change_requests_form, name='change_requests_add'),
    path('change-requests/<int:pk>/', v.change_requests_detail, name='change_requests_detail'),
    path('change-requests/<int:pk>/edit/', v.change_requests_form, name='change_requests_edit'),
    path('change-requests/<int:pk>/delete/', v.generic_delete, {'key': 'change_requests'}, name='change_requests_delete'),
    path('support-tickets/', v.support_tickets_list, name='support_tickets_list'),
    path('support-tickets/add/', v.support_tickets_form, name='support_tickets_add'),
    path('support-tickets/<int:pk>/', v.support_tickets_detail, name='support_tickets_detail'),
    path('support-tickets/<int:pk>/edit/', v.support_tickets_form, name='support_tickets_edit'),
    path('support-tickets/<int:pk>/delete/', v.generic_delete, {'key': 'support_tickets'}, name='support_tickets_delete'),

    # Reports & Admin
    path('reports/', v.reports_dashboard, name='reports_list'),
    # Packages & Subscriptions (super admin)
    path('packages/', v.packages_list, name='packages_list'),
    path('packages/add/', v.packages_form, name='packages_add'),
    path('packages/<int:pk>/', v.packages_detail, name='packages_detail'),
    path('packages/<int:pk>/edit/', v.packages_form, name='packages_edit'),
    path('packages/<int:pk>/delete/', v.generic_delete, {'key': 'packages'}, name='packages_delete'),
    path('subscriptions/', v.subscriptions_list, name='subscriptions_list'),
    path('subscriptions/add/', v.subscriptions_form, name='subscriptions_add'),
    path('subscriptions/<int:pk>/', v.subscriptions_detail, name='subscriptions_detail'),
    path('subscriptions/<int:pk>/edit/', v.subscriptions_form, name='subscriptions_edit'),
    path('subscriptions/<int:pk>/delete/', v.generic_delete, {'key': 'subscriptions'}, name='subscriptions_delete'),
    path('settings/', v.settings_view, name='settings_list'),
    path('settings/<int:pk>/', v.settings_form, name='settings_detail'),
    path('settings/<int:pk>/edit/', v.settings_form, name='settings_edit'),
    path('settings/<int:pk>/delete/', v.generic_delete, {'key': 'settings'}, name='settings_delete'),
    path('users/', v.users_list, name='users_list'),
    path('users/add/', v.users_form, name='users_add'),
    path('users/<int:pk>/', v.users_detail, name='users_detail'),
    path('users/<int:pk>/edit/', v.users_form, name='users_edit'),
    path('users/<int:pk>/delete/', v.generic_delete, {'key': 'users'}, name='users_delete'),
    path('roles/', v.roles_list, name='roles_list'),
    path('roles/add/', v.roles_form, name='roles_add'),
    path('roles/<int:pk>/', v.roles_detail, name='roles_detail'),
    path('roles/<int:pk>/edit/', v.roles_form, name='roles_edit'),
    path('roles/<int:pk>/delete/', v.generic_delete, {'key': 'roles'}, name='roles_delete'),
    path('departments/', v.departments_list, name='departments_list'),
    path('departments/add/', v.departments_form, name='departments_add'),
    path('departments/<int:pk>/', v.departments_detail, name='departments_detail'),
    path('departments/<int:pk>/edit/', v.departments_form, name='departments_edit'),
    path('departments/<int:pk>/delete/', v.generic_delete, {'key': 'departments'}, name='departments_delete'),
    path('designations/', v.designations_list, name='designations_list'),
    path('designations/add/', v.designations_form, name='designations_add'),
    path('designations/<int:pk>/', v.designations_detail, name='designations_detail'),
    path('designations/<int:pk>/edit/', v.designations_form, name='designations_edit'),
    path('designations/<int:pk>/delete/', v.generic_delete, {'key': 'designations'}, name='designations_delete'),

    # Client Portal
    path('portal/', v.portal_dashboard, name='portal_dashboard'),
    path('portal/projects/', v.portal_projects, name='portal_projects'),
    path('portal/invoices/', v.portal_invoices, name='portal_invoices'),
    path('portal/documents/', v.portal_documents, name='portal_documents'),
    path('portal/tickets/', v.portal_tickets, name='portal_tickets'),
]
