# Generated by Django 5.2.14 on 2026-05-26 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='company_admin',
            field=models.ForeignKey(blank=True, help_text="Company admin who has full access to this company's data", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_of_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='category',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('company_admin', 'Company Admin'), ('management', 'Management / Director'), ('delivery_manager', 'Delivery Manager'), ('project_manager', 'Project Manager'), ('account_manager', 'Account Manager'), ('employee', 'Employee'), ('hr_manager', 'HR / Resource Manager'), ('finance_user', 'Finance User'), ('client_admin', 'Client Admin'), ('client_user', 'Client User')], max_length=50),
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_system_role',
            field=models.BooleanField(default=False, help_text='System roles cannot be deleted'),
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('company_admin', 'Company Admin'), ('management', 'Management / Director'), ('delivery_manager', 'Delivery Manager'), ('project_manager', 'Project Manager'), ('account_manager', 'Account Manager'), ('employee', 'Employee'), ('hr_manager', 'HR / Resource Manager'), ('finance_user', 'Finance User'), ('client_admin', 'Client Admin'), ('client_user', 'Client User')], default='employee', max_length=50),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(help_text="Unique identifier e.g. 'projects', 'clients', 'timesheets'", max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text="CSS class for icon e.g. 'fas fa-project-diagram'", max_length=100)),
                ('path', models.CharField(blank=True, help_text="Frontend route path e.g. '/projects'", max_length=500)),
                ('sequence', models.IntegerField(default=0)),
                ('is_menu_item', models.BooleanField(default=True, help_text='Show in navigation menu')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user_management.module')),
            ],
            options={
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text="e.g. 'view_projects', 'create_tasks'", max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('permission_type', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('approve', 'Approve'), ('export', 'Export'), ('import', 'Import'), ('assign', 'Assign'), ('manage', 'Manage')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='user_management.module')),
            ],
            options={
                'ordering': ['module', 'permission_type'],
                'unique_together': {('module', 'codename')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='user_management.permission'),
        ),
    ]
