# Generated by Django 5.2.14 on 2026-05-26 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_company_options_company_company_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text="Unique code e.g. 'starter', 'pro', 'enterprise'", max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=False, help_text='Free package has no billing')),
                ('user_limit', models.IntegerField(default=5)),
                ('client_limit', models.IntegerField(default=20)),
                ('project_limit', models.IntegerField(default=20)),
                ('storage_limit_mb', models.IntegerField(default=512)),
                ('trial_days', models.IntegerField(default=14)),
                ('features', models.TextField(blank=True, help_text='JSON list of feature descriptions')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='client_limit',
            field=models.IntegerField(default=50, help_text='Maximum number of clients allowed'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('enterprise', 'Enterprise'), ('startup', 'Startup'), ('agency', 'Agency'), ('freelancer', 'Freelancer'), ('other', 'Other')], default='enterprise', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='project_limit',
            field=models.IntegerField(default=50, help_text='Maximum number of projects allowed'),
        ),
        migrations.AddField(
            model_name='company',
            name='storage_limit_mb',
            field=models.IntegerField(default=1024, help_text='Storage limit in MB'),
        ),
        migrations.AddField(
            model_name='company',
            name='storage_used_mb',
            field=models.IntegerField(default=0, help_text='Storage used in MB'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='user_limit',
            field=models.IntegerField(default=10, help_text='Maximum number of users allowed'),
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('paid_via', models.CharField(blank=True, help_text='Payment gateway or method', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='user_management.company')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='user_management.package')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(default='company_admin', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invites', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='user_management.company')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'email')},
            },
        ),
    ]
