# Generated by Django 5.2.14 on 2026-05-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_package_company_client_limit_company_company_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='working_days',
            field=models.CharField(blank=True, default='Mon,Tue,Wed,Thu,Fri', help_text='Comma-separated working days', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='working_hours',
            field=models.CharField(blank=True, default='9:00 AM - 6:00 PM', help_text='Working hours range', max_length=100),
        ),
    ]
