# Generated by Django 5.2.14 on 2026-05-26 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('client_crm', '0001_initial'),
        ('project_360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmilestone',
            name='milestone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_milestone', to='project_360.projectmilestone'),
        ),
        migrations.AddField(
            model_name='billingmilestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_milestones', to='project_360.project'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.billingmilestone'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='client_crm.client'),
        ),
    ]
