# Generated by Django 5.2.14 on 2026-05-26 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_crm', '0002_initial'),
        ('user_management', '0002_alter_company_options_company_company_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='user_management.company'),
        ),
    ]
