# Generated by Django 5.2.14 on 2026-05-26 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_operations', '0002_initial'),
        ('user_management', '0002_alter_company_options_company_company_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='user_management.company'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='user_management.company'),
        ),
    ]
