# Generated by Django 5.2.14 on 2026-05-26 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(choices=[('internal', 'Internal Project Meeting'), ('client_review', 'Client Review Meeting'), ('steering', 'Steering Committee Meeting'), ('technical', 'Technical Discussion'), ('uat', 'UAT Meeting'), ('kickoff', 'Kickoff Meeting'), ('closure', 'Closure Meeting'), ('other', 'Other')], default='internal', max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('meeting_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_link', models.URLField(blank=True, help_text='Virtual meeting link')),
                ('agenda', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('minutes', models.TextField(blank=True)),
                ('minutes_document', models.FileField(blank=True, null=True, upload_to='meeting_minutes/')),
                ('is_client_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-meeting_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('approval', 'Approval Required'), ('reminder', 'Reminder')], default='info', max_length=20)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('sow', 'SOW'), ('contract', 'Contract'), ('proposal', 'Proposal'), ('project_plan', 'Project Plan'), ('brd', 'BRD'), ('fsd', 'FSD'), ('technical', 'Technical Document'), ('meeting_minutes', 'Meeting Minutes'), ('uat', 'UAT Document'), ('sign_off', 'Sign-Off'), ('invoice', 'Invoice'), ('payment_proof', 'Payment Proof'), ('client_doc', 'Client Document'), ('internal_note', 'Internal Note'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('version', models.CharField(blank=True, max_length=20)),
                ('visibility', models.CharField(choices=[('internal', 'Internal Only'), ('client_visible', 'Client Visible'), ('management', 'Management Only'), ('team', 'Project Team Only')], default='internal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_documents', to='client_crm.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
