# Generated by Django 5.2.14 on 2026-05-26 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings_documents', '0001_initial'),
        ('project_360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='project_360.project'),
        ),
    ]
