# Generated by Django 5.2.14 on 2026-05-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('impact_analysis', 'Impact Analysis'), ('management_review', 'Management Review'), ('client_approval', 'Client Approval Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], default='draft', max_length=30)),
                ('impact_on_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('impact_on_timeline', models.IntegerField(blank=True, help_text='Number of days added', null=True)),
                ('impact_on_resources', models.TextField(blank=True)),
                ('estimated_effort', models.DecimalField(blank=True, decimal_places=2, help_text='Hours', max_digits=10, null=True)),
                ('client_approved', models.BooleanField(default=False)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('issue_type', models.CharField(choices=[('bug', 'Bug'), ('blocker', 'Blocker'), ('dependency', 'Dependency'), ('client_delay', 'Client Delay'), ('resource_issue', 'Resource Issue'), ('technical', 'Technical Issue'), ('scope_issue', 'Scope Issue'), ('payment_issue', 'Payment Issue'), ('approval_delay', 'Approval Delay'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('cosmetic', 'Cosmetic')], default='major', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_client_visible', models.BooleanField(default=True)),
                ('target_resolution_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('probability', models.CharField(choices=[('very_high', 'Very High - 80-100%'), ('high', 'High - 60-80%'), ('medium', 'Medium - 40-60%'), ('low', 'Low - 20-40%'), ('very_low', 'Very Low - 0-20%')], default='medium', max_length=20)),
                ('impact', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('risk_score', models.IntegerField(default=0, help_text='Calculated risk score (1-25)')),
                ('mitigation_plan', models.TextField(blank=True)),
                ('contingency_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('assessing', 'Assessing'), ('mitigating', 'Mitigating'), ('monitoring', 'Monitoring'), ('closed', 'Closed')], default='identified', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('is_client_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_on_client', 'Waiting on Client'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
